apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
  name: postgresql-nodeport-svc
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
    nodePort: 32432
  selector:
    app: postgresql
  type: NodePort